<?php

$routing = [
    '/' => 'glowna',
    '/glowna' => 'glowna',
    '/upload' => 'upload',
    '/galeria' => 'galeria',
    '/uploadZdjecia' => 'uploadZdjecia',
    '/zdjecie' => 'zdjecie',
    '/zdjecieShow' => 'zdjecieShow',
    '/nastepnaStrona' => 'nastepnaStrona',
    '/poprzedniaStrona' => 'poprzedniaStrona',
    '/rejestracja' => 'rejestracja',
    '/login' => 'login',
    '/konto' => 'konto',
    '/utworzKonto' => 'utworzKonto',
    '/logowanieUser' => 'logowanieUser',
    '/wyloguj' => 'wyloguj',
    '/zapiszZdj' => 'zapiszZdj',
    '/zapisane' => 'zapisane',
    '/poprzedniaStronaZapis' => 'poprzedniaStronaZapis',
    '/nastepnaStronaZapis' => 'nastepnaStronaZapis',
    '/usunZaznaczone' => 'usunZaznaczone',
    '/zdjecieZnakWodny' => 'zdjecieZnakWodny',
];
